from types import position, nucleotide, aa

GENOME_COORD_COLUMNS = ["CHR", "STRAND", "START", "REF", "ALT", "TRANSCRIPT" ]
GENOME_COORD_TYPES = [str, str, position, nucleotide, nucleotide, str]
GENOME_COORD_COLUMN_TYPE = dict(zip(GENOME_COORD_COLUMNS, GENOME_COORD_TYPES))
GENOME_COORD_REQ_COLUMNS = ["CHR", "START", "ALT"]

PROTEIN_COORD_COLUMNS = ["PROTEIN", "AA_POS", "AA_REF", "AA_ALT"]
PROTEIN_COORD_TYPES = [str, position, aa, aa]
PROTEIN_COORD_COLUMN_TYPE = dict(zip(PROTEIN_COORD_COLUMNS, PROTEIN_COORD_TYPES))
PROTEIN_COORD_REQ_COLUMNS = ["PROTEIN", "AA_POS", "AA_ALT"]

COORD_COLUMNS = GENOME_COORD_COLUMNS + PROTEIN_COORD_COLUMNS
COORD_TYPES = GENOME_COORD_TYPES + PROTEIN_COORD_TYPES
COORD_COLUMN_TYPE = dict(zip(COORD_COLUMNS, COORD_TYPES))